version: "3.8"

services:
  nodejs:
    image: nodejs-app
    container_name: nodejs-server
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000